language: python
python:
- '3.6'
install: python setup.py install
script: nosetests
deploy:
  provider: pypi
  user: ostapsteam
  server: https://test.pypi.org/legacy/
  password:
    secure: w4+4JYkuVxxmbuP2VJl90ZFi2j/d4qb6slGIJI38lHJr73Vx1A4lykbFSXnRBOaaF+Un/VDtZacAjDDEW2cnd8ItJmbfrfZJvQeQ59HP1uSGy/i3yeEXrnrBB4TWxSNm1CNfFMbuRbE4o6XMLu7xDNfRQsmehJQY4o8qoktnzvOfKSbmoJ7HZXSvjdu/W56a9GXQcjtE3pH62rnrYLiZdLnU7Ha3MpYzZpPQlMANzi7zNd3tre37j+b8Be1g5HWPi/vNlnU0a9GbdJFUYjO3DlsYExgpNiZx9iAGnm93Tiv8lKpII/U2vaMMgaJ6AnQJmXAaXdBHvSj9vsvhcmIpBBGYmBv7QmnmwUbFE5M8pCHeJ5mj366x0xTXZaMELVTBNxv5YrodBpmtAP01qH0dFPQpXQm5lplDh6UsUlKBxFBe4Jw1SJKjTpPLULSV2JkVre0tpDzTy5S9W1DCzSGm6vgJC6N2TXSEYmtUuLmVQnwVU4/qBPLrPPDzpj2U42s33xlgRaBACIeWp7SFx8p3+67VRlAWtXwc0sxMscPuaJx+PV9BPgjrFgtZEg6o/oHwrDGrhCsiTqDclRiDln13xKoi/vYBN+QAuydKzXzaQwL3oWwT+Yz3ruMG/YaXJOm1uOVKNZnO3Qgi3MrtpY2TJ1Bzg1fycSB6OWp+QQaE+SI=
  on:
    distributions: sdist bdist_wheel
    repo: ostapsteam/bugr
    branch: master
